name: Deploy Backend to Production


on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-backend-prod:
    runs-on: ubuntu-latest
    environment: PROD
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_KEY }}
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Install Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Deploy to Cloud Run (Production)
      env:
        CLOUD_RUN_SERVICE_ACCOUNT_KEY: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT_KEY }}
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        APPLICATION_VANITY_DOMAIN: ${{ secrets.APPLICATION_VANITY_DOMAIN }}
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_REGION: ${{ secrets.GCP_REGION }}
        GCP_API_NAME: ${{ secrets.GCP_API_NAME }}
        GCP_API_REPO_NAME: ${{ secrets.GCP_API_REPO_NAME }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      run: |
        chmod +x backend/deployment/deploy-backend.sh
        ./backend/deployment/deploy-backend.sh --env PROD